---
- name: Create an arbitrated replicated volume
  hosts: all
  remote_user: root
  gather_facts: false

  vars:
    gluster_cluster_hosts:
      - vm2
      - vm3
      - vm4
    gluster_cluster_volume: ansi_vol
    gluster_cluster_replica_count: 3
    gluster_cluster_arbiter_count: 1
    gluster_cluster_force: 'yes'
    gluster_cluster_transport: 'tcp'
    gluster_cluster_bricks: '/mnt'

  roles:
    - gluster.cluster
